[workspace]
resolver = "2"
members = [
    # Libs
    "lib",
    # Services
    "services/acl-service", "services/files",
]

[profile.release]
strip = true # Automatically strip symbols from the binary.
