version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  tt-shared-service:
    image: elonaire/tt-shared-service:latest
    pull_policy: always
    # ports:
    #   - 3002:3002
    # container_name: tt-shared-service
    networks:
      - app-tier
    volumes:
      - ./services/shared-service/database/schemas/schemas.surql:/usr/src/db/schemas.surql
      - ./services/shared-service/posts:/usr/src/posts
    environment:
      - DATABASE_NAMESPACE=${DATABASE_NAMESPACE}
      - DATABASE_NAME_SHARED=${DATABASE_NAME_SHARED}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST_SHARED=${DATABASE_HOST_SHARED}
      - DATABASE_PORT_SHARED=${DATABASE_PORT_SHARED}
      - OAUTH_SERVICE=${OAUTH_SERVICE}
      - DATABASE_SCHEMA_FILE_PATH=${DATABASE_SCHEMA_FILE_PATH}
      - BLOG_POSTS_DIR=${BLOG_POSTS_DIR}

volumes:
    tt-shared-servicedb: