version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  tt-shared-service:
    image: elonaire/tt-shared-service:latest
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: shared-service
        PORT: 3002