version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  gateway:
    image: nginx:latest
    # container_name: gateway
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
    ports:
      - "80-89:80"
      - "443-452:443" # Uncomment this line if you want to use https
    depends_on:
      - tt-acl-service
      - tt-shared-service
      - tt-frontend
    volumes:
      - /etc/ssl/certs:/etc/nginx/certs # Uncomment this line if you want to use https
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx:/var/log/nginx
    networks:
      - app-tier
  tt-frontend:
    image: elonaire/tt-frontend:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - 8080:8080
    container_name: tt-frontend
    depends_on:
      - tt-acl-service
      - tt-shared-service
    networks:
      - app-tier
  tt-acl-db:
    image: surrealdb/surrealdb:v1.5.1
    restart: unless-stopped
    ports:
      - 8000:8000
    container_name: tt-acl-db
    networks:
      - app-tier
    user: root
    command: start --log debug --auth --user ${DATABASE_USER} --pass ${DATABASE_PASSWORD} file:/db-data/mydatabase.db
    volumes:
      - tt-acl-servicedb:/db-data
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  tt-shared-servicedb:
    image: surrealdb/surrealdb:v1.5.1
    restart: unless-stopped
    ports:
      - 8001:8001
    container_name: tt-shared-servicedb
    networks:
      - app-tier
    user: root
    command: start --log debug --auth --user ${DATABASE_USER} --pass ${DATABASE_PASSWORD} --bind 0.0.0.0:8001 file:/db-data/mydatabase.db
    volumes:
      - tt-shared-servicedb:/db-data
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  tt-acl-service:
    image: elonaire/tt-acl-service:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - 3001:3001
    container_name: tt-acl-service
    networks:
      - app-tier
    depends_on:
      - tt-acl-db
  tt-shared-service:
    image: elonaire/tt-shared-service:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - 3002:3002
    container_name: tt-shared-service
    networks:
      - app-tier
    depends_on:
      - tt-acl-service
      - tt-shared-servicedb