version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  tt-acl-db:
    image: surrealdb/surrealdb:v1.5.1
    # ports:
    #   - 8000:8000
    container_name: tt-acl-db
    networks:
      - app-tier
    user: root
    command: start --log debug --auth --user ${DATABASE_USER} --pass ${DATABASE_PASSWORD} file:/db-data/mydatabase.db
    volumes:
      - tt-acl-servicedb:/db-data
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  tt-acl-service:
    image: elonaire/tt-acl-service:latest
    pull_policy: always
    # ports:
    #   - 3001:3001
    container_name: tt-acl-service
    networks:
      - app-tier
    volumes:
      - ./services/acl-service/database/schemas/schemas.surql:/usr/src/db/schemas.surql
    environment:
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - GOOGLE_OAUTH_AUTHORIZE_URL=${GOOGLE_OAUTH_AUTHORIZE_URL}
      - GOOGLE_OAUTH_ACCESS_TOKEN_URL=${GOOGLE_OAUTH_ACCESS_TOKEN_URL}
      - GOOGLE_OAUTH_REVOKE_TOKEN_URL=${GOOGLE_OAUTH_REVOKE_TOKEN_URL}
      - GITHUB_OAUTH_CLIENT_ID=${GITHUB_OAUTH_CLIENT_ID}
      - GITHUB_OAUTH_CLIENT_SECRET=${GITHUB_OAUTH_CLIENT_SECRET}
      - GITHUB_OAUTH_AUTHORIZE_URL=${GITHUB_OAUTH_AUTHORIZE_URL}
      - GITHUB_OAUTH_ACCESS_TOKEN_URL=${GITHUB_OAUTH_ACCESS_TOKEN_URL}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}
      - DATABASE_NAMESPACE=${DATABASE_NAMESPACE}
      - DATABASE_NAME_ACL=${DATABASE_NAME_ACL}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST_ACL=${DATABASE_HOST_ACL}
      - DATABASE_PORT_ACL=${DATABASE_PORT_ACL}
      - DATABASE_SCHEMA_FILE_PATH=${DATABASE_SCHEMA_FILE_PATH}
      - SHARED_SERVICE=${SHARED_SERVICE}
    depends_on:
      - tt-acl-db

# Add any network or volume configurations if needed
volumes:
  tt-acl-servicedb:
