version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  tt-acl-service:
    image: elonaire/tt-acl-service:latest
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: acl-service
  