[package]
name = "lib"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[dependencies]
cookie = { workspace = true }
async-graphql = { workspace = true }
serde = { workspace = true }
axum = { workspace = true }
surrealdb = { workspace = true }
hyper = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
prost = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
tonic-middleware = { workspace = true }
rumqttc = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
